language: php
sudo: false
dist: trusty

php:
  - 7.1

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv

script: composer validate

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      install:
        - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
        - travis_retry composer require --update-with-dependencies --prefer-dist squizlabs/php_codesniffer:^3.0
      script: vendor/bin/phpcs
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      install:
        - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
        - travis_retry composer require --update-with-dependencies --prefer-dist friendsofphp/php-cs-fixer:^2.5
      script: vendor/bin/php-cs-fixer fix --dry-run -vv
    - stage: static code analysis
      php: 7.1
      env: COMPOSER_FLAGS=""
      install:
        - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
        - travis_retry composer require --update-with-dependencies --prefer-dist phpstan/phpstan:0.8.4
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src web bin tests

notifications:
  email: false
