language: php
sudo: false
dist: trusty

php:
  - 7.1

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $COMPOSER_FLAGS -vv

script: composer validate

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - travis_retry composer self-update
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS="--no-dev"
      script: wget https://github.com/squizlabs/PHP_CodeSniffer/releases/download/3.0.2/phpcs.phar && php -n phpcs.phar
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS="--no-dev"
      script: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.5.0/php-cs-fixer.phar && php -n php-cs-fixer.phar fix --dry-run -vv

notifications:
  email: false
