language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

os:
  - linux
  - windows

env:
  - COMPOSER_FLAGS="--prefer-lowest --ignore-platform-reqs"
  - COMPOSER_FLAGS="--ignore-platform-reqs"

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - composer validate
  - static code analysis

before_install:
  - stty cols 130
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script: skip

jobs:
  allow_failures:
    - php: 7.3
    - php: nightly
    - os: windows
  include:
    - stage: composer validate
      php: 7.1
      os: linux
      install: skip
      script:
        - composer validate

    - stage: static code analysis
      php: 7.1
      os: linux
      env:
        - TEST=phpcs
        - COMPOSER_FLAGS="--ignore-platform-reqs"
      script: vendor/bin/phpcs --colors

    - stage: static code analysis
      php: 7.1
      os: linux
      env:
        - TEST=php-cs-fixer
        - COMPOSER_FLAGS="--ignore-platform-reqs"
      script: vendor/bin/php-cs-fixer fix --dry-run -vv

    - stage: static code analysis
      php: 7.1
      os: linux
      env:
        - TEST=phpstan
        - COMPOSER_FLAGS="--ignore-platform-reqs"
      script: vendor/bin/phpstan analyse -l max -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src

notifications:
  email: false
