language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script: composer validate

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: vendor/bin/phpcs --colors
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: vendor/bin/php-cs-fixer fix --dry-run -vv
    - stage: static code analysis
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src web bin

notifications:
  email: false
